import logging
import asyncio
from typing import List, Dict, Any
from urllib.parse import urlparse
from uuid import UUID

from app.core.config import settings
from app.models.session import SessionStatus
from app.models.event import EventType
from app.models.fetched_page import FetchedPage
from app.models.page_knowledge import PageKnowledge
from app.models.coordinator import (
    IterativeResearchRoundMetrics,
    IterativeResearchRunResult,
)

logger = logging.getLogger(__name__)


class IterativeCoordinatorError(Exception):
    """Base exception for IterativeResearchCoordinator failures."""
    pass


class IterativeResearchCoordinator:
    """
    Orchestration service that coordinates the multi-round iterative research loop.
    Repeatedly searches, fetches, analyzes pages, updates the knowledge base,
    discovers gaps, and plans followup queries until the confidence threshold is met
    or maximum rounds are reached.
    """

    def __init__(
        self,
        llm_service,
        search_service,
        scraper_service,
        page_understanding_service,
        knowledge_builder_service,
        gap_discovery_service,
        research_planner_service,
        event_bus,
        session_repo,
        query_repo,
        search_result_repo,
        fetched_page_repo,
        page_knowledge_repo,
        knowledge_repo,
        gap_repo,
        followup_repo,
    ):
        self.llm_service = llm_service
        self.search_service = search_service
        self.scraper_service = scraper_service
        self.page_understanding_service = page_understanding_service
        self.knowledge_builder_service = knowledge_builder_service
        self.gap_discovery_service = gap_discovery_service
        self.research_planner_service = research_planner_service
        self.event_bus = event_bus
        self.session_repo = session_repo
        self.query_repo = query_repo
        self.search_result_repo = search_result_repo
        self.fetched_page_repo = fetched_page_repo
        self.page_knowledge_repo = page_knowledge_repo
        self.knowledge_repo = knowledge_repo
        self.gap_repo = gap_repo
        self.followup_repo = followup_repo

    async def run_iterative_research(
        self,
        question: str,
        max_rounds: int = None,
        confidence_threshold: float = None
    ) -> IterativeResearchRunResult:
        """
        Runs the iterative research loop for the given question.
        """
        # Resolve configurations
        if max_rounds is None:
            max_rounds = settings.MAX_RESEARCH_ROUNDS
        if confidence_threshold is None:
            confidence_threshold = settings.CONFIDENCE_THRESHOLD

        # 1. Create Session
        session = await self.session_repo.create_session(question=question)
        session_id = session.id

        await self.event_bus.publish(
            EventType.SESSION_CREATED, session_id,
            {"question": question},
        )
        await self.event_bus.publish(
            EventType.RESEARCH_STARTED, session_id,
            {"question": question},
        )

        # Update status to RUNNING
        await self.session_repo.update_status(session_id, SessionStatus.RUNNING)

        round_metrics: List[IterativeResearchRoundMetrics] = []
        stopped_reason = "max_rounds_reached"
        final_confidence = 0.0
        final_coverage = 0.0

        current_queries: List[str] = []

        try:
            for round_idx in range(max_rounds):
                # Fetch node count before starting the round to measure growth
                nodes_before = await self.knowledge_repo.get_nodes_by_session(session_id)
                node_count_before = len(nodes_before)

                # Step 1: Resolve Search Queries
                if round_idx == 0:
                    try:
                        current_queries = await self.llm_service.generate_queries(question)
                    except Exception as e:
                        raise IterativeCoordinatorError(f"Query generation step failed in round 0: {e}")
                else:
                    # In subsequent rounds, get followup queries planned in the previous round
                    # (we retrieve the queries persisted at the end of the previous round)
                    round_followups = await self.followup_repo.get_by_session(session_id)
                    # To only query new followups planned in the prior round, filter by recent ones
                    # or keep the ones generated by the planner step. We can simply use the planning list
                    # from the previous loop's in-memory variable `followup_queries`.
                    if not followup_queries:
                        logger.info("No followup queries generated in previous round. Stopping.")
                        stopped_reason = "no_more_queries"
                        break
                    current_queries = [fq.query for fq in followup_queries]

                if not current_queries:
                    logger.info("No queries to search in this round. Stopping.")
                    stopped_reason = "no_more_queries"
                    break

                # Publish Event
                await self.event_bus.publish(
                    EventType.RESEARCH_ROUND_STARTED,
                    session_id=session_id,
                    payload={"round": round_idx, "queries": current_queries}
                )

                # Persist queries as GeneratedQuery records
                query_records = []
                for query_text in current_queries:
                    q_rec = await self.query_repo.create_query(session_id=session_id, query_text=query_text)
                    query_records.append(q_rec)

                # Step 2: Search
                all_results = []
                try:
                    for q_rec in query_records:
                        raw_results = await self.search_service.search(query=q_rec.query_text)
                        for r in raw_results:
                            r.query_id = q_rec.id
                            all_results.append(r)
                except Exception as e:
                    raise IterativeCoordinatorError(f"Search step failed in round {round_idx}: {e}")

                # Deduplicate results by URL
                unique_results_map = {}
                for r in all_results:
                    url = r.url
                    if url not in unique_results_map or r.score > unique_results_map[url].score:
                        unique_results_map[url] = r
                deduplicated_results = list(unique_results_map.values())

                # Persist search results
                await self.search_result_repo.create_many(deduplicated_results)

                # Step 3: Fetch Pages
                await self.scraper_service.start()
                try:
                    semaphore = asyncio.Semaphore(settings.MAX_CONCURRENT_FETCHES)

                    async def _bounded_fetch(url: str):
                        async with semaphore:
                            return await self.scraper_service.fetch_and_extract(url)

                    tasks = [_bounded_fetch(sr.url) for sr in deduplicated_results]
                    page_contents = await asyncio.gather(*tasks)
                except Exception as e:
                    raise IterativeCoordinatorError(f"Fetching pages failed in round {round_idx}: {e}")
                finally:
                    await self.scraper_service.stop()

                # Build and persist FetchedPage records
                fetched_pages = []
                for sr, pc in zip(deduplicated_results, page_contents):
                    fetched_page = FetchedPage(
                        search_result_id=sr.id,
                        url=pc.url,
                        canonical_url=pc.canonical_url,
                        title=pc.title,
                        content=pc.content,
                        content_hash=pc.content_hash,
                        content_length=pc.content_length,
                        raw_html_path=pc.raw_html_path,
                        extraction_quality_score=pc.extraction_quality_score,
                        fetch_status=pc.fetch_status,
                        error_message=pc.error_message,
                        metadata_=pc.metadata_,
                    )
                    fetched_pages.append(fetched_page)

                await self.fetched_page_repo.create_many(fetched_pages)

                successful_pages = [
                    fp for fp in fetched_pages if fp.fetch_status == "success"
                ]
                successful_pages = successful_pages[:settings.MAX_CLAIM_EXTRACTION_PAGES]

                # Step 4: Analyze Pages (PageKnowledge)
                round_knowledges = []
                try:
                    for page in successful_pages:
                        res = await self.page_understanding_service.analyze_page(page.content)
                        import json
                        knowledge = PageKnowledge(
                            page_id=page.id,
                            session_id=session_id,
                            summary=res["summary"],
                            key_points=json.dumps(res["key_points"]),
                            main_topics=json.dumps(res["main_topics"]),
                            entities=json.dumps(res["entities"]),
                            importance_score=res["importance_score"],
                        )
                        round_knowledges.append(knowledge)
                except Exception as e:
                    raise IterativeCoordinatorError(f"Page analysis failed in round {round_idx}: {e}")

                await self.page_knowledge_repo.create_many(round_knowledges)

                # Step 5: Update/Build Knowledge Graph (KnowledgeNode & KnowledgeEdge)
                all_page_knowledges = await self.page_knowledge_repo.get_by_session(session_id)
                try:
                    nodes_list, edges_list = await self.knowledge_builder_service.build_knowledge_graph(
                        session_id, all_page_knowledges
                    )
                except Exception as e:
                    raise IterativeCoordinatorError(f"Knowledge Graph builder failed in round {round_idx}: {e}")

                # Clear previous nodes & edges, and persist new ones
                await self.knowledge_repo.clear_session_graph(session_id)
                persisted_nodes = await self.knowledge_repo.create_nodes(nodes_list)
                persisted_edges = await self.knowledge_repo.create_edges(edges_list)

                # Step 6: Find Gaps (ResearchGaps)
                try:
                    discovery_result = await self.gap_discovery_service.find_research_gaps(
                        session_id=session_id,
                        question=question,
                        nodes=persisted_nodes,
                        edges=persisted_edges
                    )
                except Exception as e:
                    raise IterativeCoordinatorError(f"Gap discovery failed in round {round_idx}: {e}")

                # Clear old gaps and persist new ones
                await self.gap_repo.clear_session_gaps(session_id)
                persisted_gaps = await self.gap_repo.create_many(discovery_result["gaps"])

                # Step 7: Generate Followup Queries (FollowupQueries)
                try:
                    followup_queries = await self.research_planner_service.generate_followup_queries(
                        session_id=session_id,
                        question=question,
                        nodes=persisted_nodes,
                        edges=persisted_edges,
                        gaps=persisted_gaps
                    )
                except Exception as e:
                    raise IterativeCoordinatorError(f"Planning mockup queries failed in round {round_idx}: {e}")

                # Persist followup queries
                await self.followup_repo.create_many(followup_queries)

                # Compute Metrics
                known_count = len(discovery_result["known_topics"])
                missing_count = len(discovery_result["missing_topics"])
                total_topics = known_count + missing_count
                coverage = known_count / total_topics if total_topics > 0 else 0.0
                confidence = discovery_result["confidence"]
                growth = len(persisted_nodes) - node_count_before

                final_confidence = confidence
                final_coverage = coverage

                metrics = IterativeResearchRoundMetrics(
                    round_number=round_idx,
                    queries_generated=len(current_queries),
                    results_found=len(deduplicated_results),
                    pages_fetched=len(fetched_pages),
                    concepts_added=len(persisted_nodes),
                    coverage_score=coverage,
                    confidence_score=confidence,
                    knowledge_growth=growth
                )
                round_metrics.append(metrics)

                # Publish Round Completed Event
                await self.event_bus.publish(
                    EventType.RESEARCH_ROUND_COMPLETED,
                    session_id=session_id,
                    payload={
                        "round": round_idx,
                        "coverage_score": coverage,
                        "confidence_score": confidence,
                        "knowledge_growth": growth,
                    }
                )

                # Check termination
                if confidence >= confidence_threshold:
                    stopped_reason = "threshold_reached"
                    break

            # Finish iterative loop
            await self.session_repo.update_status(session_id, SessionStatus.COMPLETED)

            # Publish Stopped Event
            await self.event_bus.publish(
                EventType.RESEARCH_STOPPED,
                session_id=session_id,
                payload={
                    "reason": stopped_reason,
                    "final_confidence": final_confidence,
                    "final_coverage": final_coverage,
                }
            )
            await self.event_bus.publish(
                EventType.SESSION_COMPLETED,
                session_id=session_id,
                payload={"result": "iterative_research_completed"}
            )

            total_nodes = await self.knowledge_repo.get_nodes_by_session(session_id)

            return IterativeResearchRunResult(
                session_id=session_id,
                question=question,
                rounds_executed=len(round_metrics),
                final_coverage_score=final_coverage,
                final_confidence_score=final_confidence,
                total_concepts=len(total_nodes),
                stopped_reason=stopped_reason,
                round_metrics=round_metrics
            )

        except Exception as e:
            logger.error(f"Iterative research pipeline for session {session_id} failed: {e}", exc_info=True)
            await self.session_repo.update_status(session_id, SessionStatus.FAILED)

            await self.event_bus.publish(
                EventType.RESEARCH_FAILED,
                session_id=session_id,
                payload={"error": str(e)}
            )
            await self.event_bus.publish(
                EventType.SESSION_FAILED,
                session_id=session_id,
                payload={"error": str(e), "phase": "iterative_research_run"}
            )
            raise IterativeCoordinatorError(f"Iterative research execution failed: {e}")
