from uuid import UUID, uuid4
from typing import Optional, List, Dict, Any
from enum import Enum
from sqlmodel import SQLModel, Field
from sqlalchemy import Column, String
from sqlalchemy import Enum as SAEnum
from pydantic import BaseModel, Field as PydanticField
from app.models.base import ProvenanceMixin

class ObservationKind(str, Enum):
    METRIC = "METRIC"
    RESULT = "RESULT"
    DATASET = "DATASET"
    METHOD = "METHOD"
    ARCHITECTURE = "ARCHITECTURE"
    TRAINING = "TRAINING"
    EVALUATION = "EVALUATION"
    HYPERPARAMETER = "HYPERPARAMETER"
    LIMITATION = "LIMITATION"
    FAILURE = "FAILURE"
    ASSUMPTION = "ASSUMPTION"
    DEFINITION = "DEFINITION"
    HYPOTHESIS = "HYPOTHESIS"
    COMPARISON = "COMPARISON"
    QUOTE = "QUOTE"
    IMPLEMENTATION_DETAIL = "IMPLEMENTATION_DETAIL"
    BENCHMARK = "BENCHMARK"
    RESOURCE_REQUIREMENT = "RESOURCE_REQUIREMENT"
    ETHICS = "ETHICS"
    THREATS_TO_VALIDITY = "THREATS_TO_VALIDITY"

class ObservationPolarity(str, Enum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"
    UNKNOWN = "UNKNOWN"

class ObservationState(str, Enum):
    CANDIDATE = "CANDIDATE"
    VALIDATED = "VALIDATED"
    CANONICAL = "CANONICAL"
    DEPRECATED = "DEPRECATED"

class CandidateObservation(BaseModel):
    """
    Transient, in-memory observation generated by the LLM prompt.
    Before validation and canonicalization.
    """
    text: str = PydanticField(..., description="The observed fact")
    kind: ObservationKind
    polarity: ObservationPolarity = ObservationPolarity.UNKNOWN
    extraction_confidence: float = PydanticField(..., ge=0.0, le=1.0)
    extraction_notes: Optional[str] = PydanticField(None, description="Debugging notes for why it was extracted")
    evidence_offsets: List[Dict[str, Any]] = PydanticField(default_factory=list, description="List of text span offsets mapping to artifact")
    supporting_sentences: List[str] = PydanticField(default_factory=list)
    
    # Provenance
    prompt_hash: Optional[str] = None
    extractor_version: Optional[str] = None
    artifact_hash: Optional[str] = None
    llm_model: Optional[str] = None
    temperature: Optional[float] = None
    created_at: Optional[str] = None

class Observation(ProvenanceMixin, table=True):
    """
    Canonical, persistent observation stored in the database.
    """
    __tablename__ = "observations"
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    stable_hash: str = Field(nullable=False, index=True, unique=True, description="True identity of the observation")
    session_id: UUID = Field(foreign_key="research_sessions.id", ondelete="CASCADE", index=True)
    document_id: UUID = Field(foreign_key="parsed_documents.id", ondelete="CASCADE", index=True)
    
    kind: ObservationKind = Field(sa_column=Column(SAEnum(ObservationKind, native_enum=False), nullable=False, index=True))
    polarity: ObservationPolarity = Field(sa_column=Column(SAEnum(ObservationPolarity, native_enum=False), nullable=False, default=ObservationPolarity.NEUTRAL))
    state: ObservationState = Field(sa_column=Column(SAEnum(ObservationState, native_enum=False), nullable=False, default=ObservationState.CANDIDATE))
    
    text: str = Field(nullable=False)
    value: Optional[str] = Field(default=None)
    unit: Optional[str] = Field(default=None)
    
    # Validation Quality Metrics
    specificity_score: float = Field(default=1.0)
    grounding_score: float = Field(default=1.0)
    completeness_score: float = Field(default=1.0)
    
    # Confidence breakdown
    extraction_confidence: float = Field(default=1.0)
    grounding_confidence: float = Field(default=1.0)
    validator_confidence: float = Field(default=1.0)
    overall_confidence: float = Field(default=1.0)
    
    validator_notes: Optional[str] = Field(default=None)
    entity_id: Optional[UUID] = Field(default=None, foreign_key="entities.id", index=True)
